[debug] [2023-02-01T18:38:51.414Z] ----------------------------------------------------------------------
[debug] [2023-02-01T18:38:51.416Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\SANDEEP\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js emulators:start
[debug] [2023-02-01T18:38:51.416Z] CLI Version:   11.21.0
[debug] [2023-02-01T18:38:51.416Z] Platform:      win32
[debug] [2023-02-01T18:38:51.417Z] Node Version:  v16.17.0
[debug] [2023-02-01T18:38:51.417Z] Time:          Thu Feb 02 2023 00:08:51 GMT+0530 (India Standard Time)
[debug] [2023-02-01T18:38:51.418Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-02-01T18:38:51.422Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-02-01T18:38:51.470Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-02-01T18:38:51.471Z] > authorizing via signed-in user (mallinasandeep21@gmail.com)
[debug] [2023-02-01T18:38:56.485Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\SANDEEP\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[error] 
[error] Error: An unexpected error has occurred.
